package com.tmp.entities;
// Generated Dec 28, 2015 2:52:47 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Department generated by hbm2java
 */
public class Department implements java.io.Serializable {

	private int id;
	private String name;
	private Set students = new HashSet(0);

	public Department() {
	}

	public Department(int id) {
		this.id = id;
	}

	public Department(int id, String name, Set students) {
		this.id = id;
		this.name = name;
		this.students = students;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set getStudents() {
		return this.students;
	}

	public void setStudents(Set students) {
		this.students = students;
	}

}
