package com.tmp.entities;
// Generated Dec 28, 2015 2:52:47 PM by Hibernate Tools 4.3.1.Final

/**
 * Student generated by hbm2java
 */
public class Student implements java.io.Serializable {

	private long id;
	private Department department;
	private String name;
	private String surname;

	public Student() {
	}

	public Student(long id) {
		this.id = id;
	}

	public Student(long id, Department department, String name, String surname) {
		this.id = id;
		this.department = department;
		this.name = name;
		this.surname = surname;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public Department getDepartment() {
		return this.department;
	}

	public void setDepartment(Department department) {
		this.department = department;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getSurname() {
		return this.surname;
	}

	public void setSurname(String surname) {
		this.surname = surname;
	}

}
