package com.tmp.entities;
// Generated Dec 28, 2015 2:52:47 PM by Hibernate Tools 4.3.1.Final

/**
 * Tmp generated by hbm2java
 */
public class Tmp implements java.io.Serializable {

	private int id;
	private String name;
	private int seqId;

	public Tmp() {
	}

	public Tmp(int id, int seqId) {
		this.id = id;
		this.seqId = seqId;
	}

	public Tmp(int id, String name, int seqId) {
		this.id = id;
		this.name = name;
		this.seqId = seqId;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public int getSeqId() {
		return this.seqId;
	}

	public void setSeqId(int seqId) {
		this.seqId = seqId;
	}

}
