package gov.tubitak.tutorial.hibernate.entities;
// Generated Dec 9, 2015 5:25:43 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Department generated by hbm2java
 */
@Entity
@Table(name = "department", schema = "public")
public class Department implements java.io.Serializable {

	private int id;
	private String name;
	private Set<Student> students = new HashSet<Student>(0);

	public Department() {
	}

	public Department(int id) {
		this.id = id;
	}

	public Department(int id, String name, Set<Student> students) {
		this.id = id;
		this.name = name;
		this.students = students;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false, precision = 5, scale = 0)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "department")
	public Set<Student> getStudents() {
		return this.students;
	}

	public void setStudents(Set<Student> students) {
		this.students = students;
	}

}
