package gov.tubitak.tutorial.hibernate.entities;
// Generated Dec 9, 2015 5:25:43 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Student generated by hbm2java
 */
@Entity
@Table(name = "student", schema = "public")
public class Student implements java.io.Serializable {

	private long id;
	private Department department;
	private String name;
	private String surname;

	public Student() {
	}

	public Student(long id) {
		this.id = id;
	}

	public Student(long id, Department department, String name, String surname) {
		this.id = id;
		this.department = department;
		this.name = name;
		this.surname = surname;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false, precision = 10, scale = 0)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "dpt_id")
	public Department getDepartment() {
		return this.department;
	}

	public void setDepartment(Department department) {
		this.department = department;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "surname")
	public String getSurname() {
		return this.surname;
	}

	public void setSurname(String surname) {
		this.surname = surname;
	}

}
