package gov.tubitak.tutorial.hibernate.entities;
// Generated Dec 10, 2015 2:19:06 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Tmp generated by hbm2java
 */
@Entity
@Table(name = "tmp", schema = "public")
public class Tmp implements java.io.Serializable {

	private int id;
	private String name;
	private int seqId;

	public Tmp() {
	}

	public Tmp(int id, int seqId) {
		this.id = id;
		this.seqId = seqId;
	}

	public Tmp(int id, String name, int seqId) {
		this.id = id;
		this.name = name;
		this.seqId = seqId;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "seq_id", nullable = false, insertable = false, updatable = false)
	public int getSeqId() {
		return this.seqId;
	}

	public void setSeqId(int seqId) {
		this.seqId = seqId;
	}

}
